openapi: '3.0.3'
info:
  title: 'Calculator APIs'
  version: '1.0.0'
tags:
  - name : health
    description: Health check
  - name : calculator
    description : Calculator operations
externalDocs:
  url: http://localhost:3000
  description: Calculator APIs documentation  